### ISSUE TITLE
Graceful Shutdown

### ISSUE THREAD

**Issue by realkarmakun** [Lukas34/ShutdownTimerWin32#1]
It would be nice to have ability to do graceful shutdown, so apps can save the data if they can do that. Also I have a question, will running app prevent a computer from going to sleep?

**Comment by Lukas34** [comment]
Hi and thanks for your issue 👋.
That's a good idea, I'll try to add a graceful shutdown option. Regarding your question, no the app does not currently stop your computer from going to sleep but I'll try to implement that as well.

**Comment by Lukas34** [comment]
Okay I'll just do some testing of the new version and will release it soon. ✔
You can expect to get updated within the next week (if you are using the Microsoft Store version, otherwise there will be a GitHub release next week).

**Comment by realkarmakun** [comment]
Sorry for not answering. I've been away from github for a while. Thank you very much for the update and for the time you put into this!
